name: neuroconnect
channels:
  - conda-forge
dependencies:
  - numpy
  - pytest
  - pytest-cov
  - pandas
  - shiny
  - shinywidgets
  - plotly
  - nibabel
  - templateflow
  - scikit-image
  - python<=3.12
