[build-system]
requires = ["hatchling>=1.27.0"]
build-backend = "hatchling.build"

[project]
name = "neuroconnect"
version = "0.0.0"
description = "Visualization tool for structural brain connectivity, intended for Alzheimer's research"
readme = "README.md"
authors = [{name = "Tina Zhao"}]
classifiers = [
	"Intended Audience :: Science/Research",
	"Programming Language :: Python :: 3",
]
requires-python = ">=3.12"
dependencies = [
	"pandas>=2.3.0",
	"numpy",
]

[project.urls]
Homepage = "https://github.com/tinajzhao/NeuroConnect"
Issues = "https://github.com/tinajzhao/NeuroConnect/issues"