[build-system]
requires = [
	"hatching>=1.27.0"
]
build-backend = "hatching.build"

[project]
name = "NeuroConnect"
version = "0.0.0"
description = ""
readme = "README.md"
license = { file = "LICENSE" }
authors = "Tina Zhao"
classifiers = [
	'Intended Audience :: Science/Research',
	"Programming Language :: Python :: 3"
]

requires-python = ">=3.11"

dependencies = [  # packages users need to install with the package
	"Pandas >=2.3.0", "Numpy"
]


[project.urls]
Homepage = "https://github.com/tinajzhao/NeuroConnect"
Issues = "https://github.com/tinajzhao/NeuroConnect/issues"
